FROM nginx:stable-alpine

# Copy all files (not recommended for production):
COPY . /var/www/html/

# Or the minimal version (recommended):
# COPY ./public     /var/www/html/public
# COPY ./vendor     /var/www/html/vendor
# COPY ./src        /var/www/html/src
# COPY ./config     /var/www/html/config
# COPY ./composer.json /var/www/html/composer.json

COPY ./docker/nginx/default.conf.prod /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx /var/www/html/public